### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: API rate limit exceeded for user 

### ISSUE THREAD

**Issue by Chocrates** [octokit/plugin-throttling.js#218]
👋  Hey All,

This may be more of a misunderstanding on my part than a bug.  
It is related to #124 but different enough I didn't want to hijack.

I am using the octokit and the throttling plugin to write a report that will run monthly or quarterly.  
For these purposes I don't mind how long we wait for the API limits to reset (I would expect maybe a few days for the full thing to run) I just want it to respect the API limits and wait for them to reset.  

With the sample code below I am getting the below error.  I was expecting it to keep retrying until it succeeds, but it appears to only catch the first timeout and then fail.

```
Request quota exhausted for request GET https://api.github.com/repos/Chocrates/Octomock/issues?since=Tue%20Dec%2031%202019%2018%3A00%3A00%20GMT-0600%20(Central%20Standard%20Time)
Retrying after 651 seconds! Retry Count: 0
(node:20499) UnhandledPromiseRejectionWarning: HttpError: API rate limit exceeded for user ID 1758164.
    at response.text.then.message (/Users/chocrates/workspace/github-metrics/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```  

```javascript
const { Octokit } = require("@octokit/rest");
const { throttling } = require("@octokit/plugin-throttling");
const Agent = require("https").Agent;
const MyOctokit = Octokit.plugin(throttling);

const argv = require("yargs").option('base-url', { alias: 'b',
    type: 'string',
    description: 'GitHub or GitHub Enterprise base url',
    default: 'https://api.github.com',
    global: true
  })
  .option('token', {
    alias: 't',
    description: 'personal access token with which to authenticate',
    global: true,
    demandOption: true
  })
  .argv


// ugly but doesn't need async
const sleep = (duration) => {
  var now = new Date().getTime();
  while(new Date().getTime() < now + duration) {  }
}

  async function main() {
    const baseUrl = argv.baseUrl;
    const token = argv.token;

    const client =  new MyOctokit({
        auth: "token " + token,
        agent: new Agent({ rejectUnauthorized: true }),
        baseUrl,
        throttle: {
          onRateLimit: (retryAfter, options) => {
            console.warn(`Request quota exhausted for request ${options.method} ${options.url}`);
      
            if (options.request.retryCount <= 100) {
              // Still having trouble when we hit our api limit
              // Arbitrarily waiting for a minute if we hit a retry
              if(options.request.retryCount > 0){
                sleep(60000)
              }
              console.log(`Retrying after ${retryAfter} seconds! Retry Count: ${options.request.retryCount}`);
              return true;
            }
          },
          onAbuseLimit: (retryAfter, options) => {
            console.warn(`Abuse detected for request ${options.method} ${options.url}`);
          },
        },
      });

      while(true){
          console.log('Gathering issues...')
        const options = client.issues.listForRepo.endpoint.merge({owner: 'Chocrates',repo: 'Octomock', since: new Date(Date.parse('2020-01-01'))})
        const issues = await client.paginate(options)
      }

}

if (require.main == module){
    main();
}

module.exports = main;
```

Run with `node src/broke.js --token <token>`  if needed, but its a pretty dumb script.

**Comment by gr2m** [comment]
Hey @Chocrates, your assumptions map mine, I'll need some time to look into what is going on here. I'm afraid I won't have time before the week of July 6th. Let me know if that's a problem, I'll try to find some time for you before

**Comment by Chocrates** [comment]
Thanks @gr2m!

**Comment by Chocrates** [comment]
I dug in to this a bit more and it appears that we are getting a `403` with a positive rate-limit remaining strangely:

```
{
	"name": "HttpError",
	"status": 403,
	"headers": {
		"access-control-allow-origin": "*",
		"access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
		"connection": "close",
		"content-encoding": "gzip",
		"content-security-policy": "default-src 'none'",
		"content-type": "application/json; charset=utf-8",
		"date": "Fri, 26 Jun 2020 20:39:06 GMT",
		"referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
		"server": "GitHub.com",
		"status": "403 Forbidden",
		"strict-transport-security": "max-age=31536000; includeSubdomains; preload",
		"transfer-encoding": "chunked",
		"vary": "Accept-Encoding, Accept, X-Requested-With",
		"x-accepted-oauth-scopes": "repo",
		"x-content-type-options": "nosniff",
		"x-frame-options": "deny",
		"x-github-media-type": "github.v3; format=json",
		"x-github-request-id": "E28A:3562:C03202:14755B5:5EF65CEA",
		"x-oauth-scopes": "admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, read:packages, repo, user, workflow, write:discussion, write:packages",
		"x-ratelimit-limit": "5000",
		"x-ratelimit-remaining": "4999",
		"x-ratelimit-reset": "1593207546",
		"x-xss-protection": "1; mode=block"
	},
	"request": {
		"method": "GET",
		"url": "https://api.github.com/repos/Chocrates/Octomock/issues?since=Tue%20Dec%2031%202019%2018%3A00%3A00%20GMT-0600%20(Central%20Standard%20Time)",
		"headers": {
			"accept": "application/vnd.github.v3+json",
			"user-agent": "octokit-rest.js/17.11.2 octokit-core.js/2.5.4 Node.js/10.20.1 (macOS Catalina; x64)",
			"authorization": "token [REDACTED]"
		},
		"request": {
			"retryCount": 1
		}
	},
	"documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I opened PR #222 to handle it, though no idea if that is general enough for this plugin.

**Comment by gr2m** [comment]
looks like it's an API bug: https://github.com/octokit/plugin-throttling.js/pull/222#issuecomment-651256319
